language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            #Tool chains
            - cmake
            - g++-4.9
            #- g++-5
            #- g++-6
            #- g++-7

            #Thread Building Blocks
            - libtbb-dev

matrix:
    include:
        #Extensive testing for base compiler
        #- env: TESTS="basic mcnc20" TATUM_EXECUTION_ENGINE=auto C_COMP=gcc-4.9 CXX_COMP=g++-4.9
        - env: TESTS="basic mcnc20" TATUM_EXECUTION_ENGINE=serial C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9
        #- env: TESTS="basic mcnc20" TATUM_EXECUTION_ENGINE=tbb COMPILER=g++-4.9
        #- env: TESTS="basic mcnc20" TATUM_EXECUTION_ENGINE=cilk COMPILER=g++-4.9

        #Simple testing for other compilers
        #- env: TESTS="basic" TATUM_EXECUTION_ENGINE=auto COMPILER=g++-5
        #- env: TESTS="basic" TATUM_EXECUTION_ENGINE=auto COMPILER=g++-6
        #- env: TESTS="basic" TATUM_EXECUTION_ENGINE=auto COMPILER=g++-7

script:
    - mkdir -p build && pushd build && CC=$C_COMPILER CXX=$CXX_COMPILER cmake .. -DTATUM_EXECUTION_ENGINE=$TATUM_EXECUTION_ENGINE && make -j2 && popd
    - ./scripts/reg_test.py --tatum_test_exec build/tatum_test/tatum_test --tatum_nworkers 2 $TESTS
