language: c++

addons:
    apt:
        #sources:
            #- ubuntu-toolchain-r-test
        packages:
            - cmake
            - libtbb-dev
            #- gcc-4.9
            #- gcc-5
            #- gcc-6
            #- gcc-7

compiler:
    - gcc
    #- clang
    #- gcc-4.9
    #- gcc-5
    #- gcc-6
    #- gcc-7

env:
    #- TATUM_EXECUTION_ENGINE=auto
    #- TATUM_EXECUTION_ENGINE=serial
    #- TATUM_EXECUTION_ENGINE=tbb
    #- TATUM_EXECUTION_ENGINE=cilk

script:
    - make -j2
    - ./scripts/reg_test.py --tatum_test_exec build/tatum_test/tatum_test --tatum_nworkers 2 basic mcnc20
